### ISSUE TITLE
Question: Do you know you can autogenerate this from the documentation?

### ISSUE THREAD

**Issue by ejcoyle88** [mrstebo/ekm-api-php-client#19]
Hey just curious,
Are you aware that the docs are built using Swagger and output an OpenAPI compliant file?
https://api.ekm.net/swagger/v1/swagger.json

This can be used to generate clients like this in various languages, and regenerate them when the API is updated.
https://swagger.io/tools/swagger-codegen/

That's why we don't offer any of these clients ourselves. People can generate their own, which pushes maintainance and updates away from any single person.

**Comment by mrstebo** [comment]
Yeah, I did notice that the documentation is built using Swagger. I just wanted to build my own client :smile:
